name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16.x]

    steps:
      - uses: actions/checkout@v1

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      
      - uses: Azure/cli@1.0.4
        with:
           inlineScript: |
             az storage blob download --account-name wokeruleset --container-name custom-ruleset --name ruleset.yaml --file customRuleSet.yaml --sas-token ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}   
      - name: woke
        uses: get-woke/woke-action-reviewdog@v0
        with:
          fail-on-error: true
          level: error
          reporter: github-pr-review
          filter-mode: added
          woke-args: '-c customRuleSet.yaml'
